### ISSUE TITLE
Multi-database in a single Odoo server with task queue

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-docker#13]
Summary

Investigate and prototype a solution to support multiple databases on a single Odoo server, incorporating a task queue mechanism for efficient resource utilization and task management.

Objectives

- Enable a single instance of Odoo server to run multiple databases for improved resource utilization and isolation.
- Integrate a task queue to handle asynchronous tasks efficiently, prioritizing essential operations.
- Ensure the architecture is scalable and can handle an increasing number of databases and tasks.
- Measure impact on latency and throughput for different configurations and workloads.

**Comment by dasunhegoda** [comment]
@nhatnm0612 : did you try this with docker? what was the outcome?

**Comment by dasunhegoda** [comment]
https://drive.google.com/file/d/1yrICK8VTW7sctR-EvVkoBJhm92h9zh4Z/view

**Comment by nhatnm0612** [comment]
> https://drive.google.com/file/d/1yrICK8VTW7sctR-EvVkoBJhm92h9zh4Z/view

as you see in this video, both databases run queue jobs, and failed due to the error in our code [registrant gender - `Other` in the code to random generating, but not yet existed in DB]; but over all, jobs are running on multi databases setting with docker.

it is slow, due to resource restricting for docker container; and resource consumption, so I can not try it with more than 2 databases

**Comment by nhatnm0612** [comment]
[demo video](https://drive.google.com/file/d/1I4X5HiOECKOagaRKEpHBw7MU6RBV4lrm/view?usp=sharing)

this is a demo video for running job queues on multi databases with single odoo server config with docker & running by invoke task.
