### ISSUE TITLE
error invoke develop

### ISSUE THREAD

**Issue by jeremi** [OpenSPP/openspp-docker#15]
I get this when I run it the first time:
```
 $ invoke develop
Reinitialized existing Git repository in /Users/jeremi/Projects/134-openspp/spp-psnp-demo/.git/
unlink: docker-compose.yml: No such file or directory
Encountered a bad command exit code!

Command: 'cd /Users/jeremi/Projects/134-openspp/spp-psnp-demo && unlink docker-compose.yml'

Exit code: 1

Stdout: already printed

Stderr: already printed


pre-commit installed at .git/hooks/pre-commit
```

**Comment by jeremi** [comment]
@reichie020212 seems to be due to your change in `tasks.py`

**Comment by reichie020212** [comment]
@jeremi yes this error log will occur if the file docker-compose.yml is not yet existing if we execute the invoke develop.

what I did was to delete the file if it's existing or just log an error that says the file is not existing

I think these are the mistakes I did when developing this
- I used logger.error instead logger.warning
- I used the exception error message to log instead of a specific error message "docker-compose.yml is not existing."

i'll create a PR to fix this. Thank you.
